EverestAPI/CelesteTAS-EverestInterop

CelesteTAS-EverestInterop/Manager.cs, CelesteTAS-EverestInterop/everest.yaml
Mod berries extending Strawberry don't necessarily have their own `collectTimer` field, making the game crash when the TAS tools are enabled.
This PR makes the TAS tools read `collectTimer` from the parent class (Strawberry) if it doesn't exist in the strawberry's actual type.
=> Fix crashes with mod berries extending Strawberry

CelesteTAS-EverestInterop/EverestInterop/AutoMute.cs
This PR changes the "auto-mute" class so that it doesn't play sounds by not calling orig methods, instead of playing the sounds but muted. When the method should return an EventInstance, we return a shared instance of an existing vanilla sound that is silent unless you set the proper audio params on it (the footstep sound). SoundSource.Play returns `self`, since the original method does the same (it returns `this`).
This was done after reports of freezes during fast-forwarding: the freeze points were calls to FMOD, that eventually get stuck. FMOD getting overloaded can actually be heard, since music progressively stutters / gets distorted before eventually becoming silent - and that's when the fast forward starts freezing as well.
=> Don't play sounds when they are 'auto-muted' (fast-forwarding)

CelesteTAS-EverestInterop/CelesteTAS-EverestInterop.csproj, CelesteTAS-EverestInterop/EverestInterop/Benchmark.cs
This allows auto start and stop profiling when benchmarking with profiler opened
=> Wrap the benchmark with JetBrains profiler api for more accurate result

CelesteTAS-EverestInterop/Source/TAS/BindingHelper.cs, CelesteTAS-EverestInterop/Source/TAS/Input/InputFrame.cs, CelesteTAS-EverestInterop/Source/TAS/Manager.cs, Docs/Commands.md, README.md, Studio/Entities/InputRecord.cs, Studio/Studio.cs
The recent addition of the `Press` command has made TASing maps with custom inputs much easier, but they still somewhat break the flow of the TAS file and have a few other issues. This PR aims to improve the way custom inputs are handled.
The main feature of this PR is a new syntax for pressing custom inputs. The bindings are still set using the `Set` command, but they can now also be pressed in a normal input line using the `P` prefix (e.g. 15 R,X,PA presses the `A` button in addition to right and dash).
This PR also prevents custom inputs from interfering with any existing bindings by clearing all modded bindings when the TAS is run (they are restored when playback ends). Additionally, it moves the internal keybinding for the second confirm key from C to Numpad0 to prevent a confirm …
=> Improve custom keybind support

CelesteTAS-EverestInterop/Source/TAS/Input/Commands/MouseCommand.cs, CelesteTAS-EverestInterop/Source/TAS/Manager.cs, CelesteTAS-EverestInterop/Source/Utils/SpeedrunToolUtils.cs
The added "Mouse" command takes x and y coordinates within a 320x180 input space and moves the mouse accordingly. To avoid desyncs, the command only runs on window sizes that are integer upscales of the game's original 320x180 size.
Edit: Now supports clicking/holding left, middle and right mouse buttons.
=> feat: add "Mouse" command for mouse support

CelesteTAS-EverestInterop/Source/TAS/AnalogHelper.cs
.NET Framework's x86 JIT, as it turns out, isn't IEE-754 compliant, and doesn't round the 80 bit internal registers back down to 32 bits of precision after operations on floating point numbers. This can cause some operations (like the divisions modified by this patch) to execute with more precision than specified, and as such result in more accurate results than on compliant platforms. Concretely, this means that modern mono builds (which are for example used by the MacOS version of the game), 64 bit .NET Framework versions as well as .NET Core will diverge from .NET Framework, which causes a desync of the 6HC TAS in room 06 (the different `AnalogMode.Precise` behavior already affects earlier rooms, but it isn't an issue till this room).
In this case, using 64 bit double calculations …
=> fix: dependency on non IEEE 754-compilancy

CelesteTAS-EverestInterop/Source/EverestInterop/Hitboxes/HitboxColor.cs, CelesteTAS-EverestInterop/Source/EverestInterop/Hitboxes/HitboxOptimized.cs
(1).Add a more accurate hitbox indicator on puffer's PlayerCollider where player can launch/bounce
(2).Make the height check line more accurate
About (1): puffer's Explode() is also called in OnPlayer(..), and the condition is
`player.Bottom > lastSpeedPosition.Y + 3f`
different from that in puffer's ProximityExplodeCheck().
https://discord.com/channels/403698615446536203/519281383164739594/1108956272734240820
About (2): puffer's Position.Y is not integer, so the previous "when ducking, bottomCenter -= Vector2.UnitY * 3" (which should be 2.5 instead of 3) has bug (I've found such example).
Moreover, starflyHit/Hurtbox are not considered in previous implementation.
This PR addresses above issues.
=> Optimize puffer hitbox render

Studio/Studio.cs, Studio/Themes.cs, Studio/Win32Api.cs
Set the title bar color based on the selected theme.
instead of
Uses `DwmSetWindowAttribute` to set the USE_IMMERSIVE_MODE attribute to true: https://stackoverflow.com/questions/57124243/winforms-dark-title-bar-on-windows-10
=> feat(Studio): change title bar according to style

Studio/RichText/CommandManager.cs
Fixes a bug where you need to redo twice to actually redo one atomic change.
```t
1,R,U
1,R
1u,R
1,R,U
```
For background, when typing `U` on `1,R` there will be three commands pushed to the undo buffer:
```
executing command InsertCharCommand('u', autoundo=True)
executing command ClearSelectedCommand('   1u,R', autoundo=True)
executing command InsertTextCommand('   1,R,U', autoundo=False)
```
`autoundo` means that when a command is undone, if the *next* one is `autoundo` then it will also be undone.
This lets `Ctrl-Z` treat these three commands as one single undo operation.
```
undoing command InsertTextCommand('   1,R,U', autoundo=False)
- next command is ClearSelectedCommand('   1u,R', autoundo=True), undoing as well
undoing command ClearSelectedCommand('   1u,R', autoundo=True)
- next …
```
=> fix(Studio): fix broken redo

Studio/RichText/Commands.cs
https://github.com/EverestAPI/CelesteTAS-EverestInterop/assets/22177966/667d8cca-f8b4-4cf9-ac57-9bc435e7b20f
The problem was that the handling for pressing backspace to delete up to *tablength* spaces incorrectly set the `ref char deletedChar`.
The code is not really in use anyways because whitespace tabs are disabled:
https://github.com/EverestAPI/CelesteTAS-EverestInterop/blob/e889bc29a1e97c32cb5f2267006edfe64cc9d68e/Studio/Studio.Designer.cs#L1165
=> fix(Studio): fix bug where deleting a whitespace and redoing it would insert the previous char

CelesteTAS-EverestInterop/Source/EverestInterop/Core.cs
Issue was only present with hide freeze frames enabled:
When not fast forwarding, skipBaseUpdate could be true on the first iteration of the loop. But if freeze frames needed to be hidden, then OrigGameUpdate would need to be called again.
=> Bugfix: OrigGameUpdate running twice on freeze frames

CelesteTAS-EverestInterop/Source/EverestInterop/ConsoleEnhancements.cs, CelesteTAS-EverestInterop/Source/EverestInterop/InfoHUD/InfoCustom.cs, README.md
**{Player.toFrame():} will crashes the game**
as after identifying toFrame() as a helperMethod, memberNames become empty, and is never checked. Then calling memberNames.First() will crash the game
bugfix: memberNames empty exception
feat: Add GetAssembly() helperMethod
support Collider in FormatValue
rewrite FormatValue to make it more extensible
=> Bugfix: in InfoCustom, empty memberNames crashes the game

Studio/RichText/RichText.cs
You probably made a mistake while applying the patches from my fork.
It should move the playing line a bit to the left, since it's partially covered by the scroll bar on mono. However it added extra padding to the right of the line numbers on Mono instead.
=> Offset playing line instead of line nubmer on Mono

CelesteTAS-EverestInterop/Source/TAS/Input/Commands/TasCommandAttribute.cs, CelesteTAS-EverestInterop/Source/Utils/AttributeUtils.cs
AttributeUtils and TasCommandAttribute use GetCallingAssembly to access the CelesteTAS assembly. However, this can fail due to inlining (which it does on Everest Core). This PR replaces that call with a robust way of accessing the assembly.
=> Replace GetCallingAssembly to be more robust to inlining

CelesteTAS-EverestInterop/Source/EverestInterop/InfoHUD/InfoCustom.cs, CelesteTAS-EverestInterop/Source/EverestInterop/Lua/LuaHelpers.cs, CelesteTAS-EverestInterop/Source/EverestInterop/Lua/env.lua, CelesteTAS-EverestInterop/Source/TAS/Input/Commands/InvokeCommand.cs, CelesteTAS-EverestInterop/Source/TAS/Input/Commands/SetCommand.cs
feat:
1) let EvalLua getEntity command supports entityId
2) make SetCommand and InvokeCommand log warns as few as possible
e.g. "Set CustomSpinner[s1:12].X 0", it should not warn when a FrostHelper spinner[s1:12] exists but cannot find a VivHelper spinner[s1:12]
e.g. "Set CustomSpinner.X 0", it should not warn when FrostHelper spinner exists but VivHelper spinner doesn't exist
=> EntityId related enhancements on SetCommand, InvokeCommand, and EvalLua commands

CelesteTAS-EverestInterop/Source/TAS/Input/Commands/SetCommand.cs, CelesteTAS-EverestInterop/Source/Utils/ExtendedVariantsUtils.cs
Adds a special case to properly handle extended variants if the member isnt found in the settings.
Also btw, whats the reason for no longer referencing extvars directly but rather through reflection?
=> Added Extended Variants support for `Set` commands

CelesteTAS-EverestInterop/Source/TAS/Input/Commands/MetadataCommands.cs, Docs/Commands.md
Adds a `ChapterTime`/`FileTime` command, but for midway into the file.
For example: 6AC has two important chapter times: cassette collect and chapter finished.
They are called `MidwayChapterTime` and `MidwayFileTime`, which get updated when the command is executed, instead of at chapter completion/TAS ending.
The commands still have to be added to Studio, but thats probably easier for you (partially because the list goes offscreen for me lol).
NOTE: The prefix `Midway` was just the first thing which came to mind. Im sure theres something which just.. sounds a bit better?
=> Added midway chapter/file times

CelesteTAS-EverestInterop/Source/EverestInterop/SimplifiedGraphicsFeature.cs
Before:
After:
`Brokemia.PixelRendered.Vineinator` is rendered by its component `PixelComponent,` so we need to skip `PixelComponent.Render` to hide vines
`PixelComponent.DebugRender` shows in which chunks there are textures (chunks are shown as dark green squares). It is also redundant for TASers
In `BrokemiaHelper`, only `Vineinator` and `RWLizard` uses `PixelComponent`. I find that `RWLizard` actually does not have textures, and there's no Ahorn/Loenn scripts for it, so I assume `RWLizard` is actually abandoned.
In this case, hooking `PixelComponent` will only affect `Vineinator` (assume no other mods use `PixelComponent`), so that's what we want.
=> Simplified Graphics Hide Brokemia.PixelRendered.Vineinator

CelesteTAS-EverestInterop/Source/EverestInterop/DesyncFixer.cs, CelesteTAS-EverestInterop/Source/Utils/SpeedrunToolUtils.cs
As shown in the picture, the entity in GalleryCollab heartside has RNG, so this PR aims to fix it
(I've contacted AuraHelper's author and he says he will not udpate AuraHelper recently, so there's no worry that we need to revert this commit shortly after)
btw maybe this line of code
[`typeof(Entity).GetMethod("Update").HookAfter(AfterEntityUpdate);`](https://github.com/EverestAPI/CelesteTAS-EverestInterop/blob/master/CelesteTAS-EverestInterop/Source/EverestInterop/DesyncFixer.cs#L66)
can be changed to hook on `Scene.AfterUpdate` instead, but this may cause some existing tases to desync
=> Fix AuraHelper desync

CelesteTAS-EverestInterop/Source/EverestInterop/SimplifiedGraphicsFeature.cs
dash through spikes behave quite differently from normal spikes, so we shouldn't make them render samely when simplifying graphics
=> Bugfix: make dash through spikes render normally when simplifying graphics

CelesteTAS-EverestInterop/Source/TAS/Input/Commands/SaveAndQuitReenterCommand.cs
It adds a new entry between CLIMB and \~DEBUG\~ which would get selected instead.
=> Fix Randomizer causing desync with SaveAndQuitReenter

CelesteTAS-EverestInterop/Source/EverestInterop/SimplifiedGraphicsFeature.cs
Sinking Platform has a (purely visual) Shaker, which makes it hard to see the hitbox
there are some other cases where Shaker's are used in vanilla, but they look fine so i don't patch them
 
Before
After
=> Simplified Graphics Hide SinkingPlatform Shaker

StudioCommunication/ActionLine.cs, StudioCommunication/CommunicationAdapterBase.cs, StudioCommunication/NetStandardPolyfill.cs, StudioCommunication/StudioCommunication.csproj, StudioCommunication/Util/BinaryHelper.cs, StudioCommunication/Util/CommonExtensions.cs, StudioCommunication/Util/EnumArray.cs, StudioCommunication/Util/ProcessHelper.cs
I'm trying to make studio interface work with another game, and for that I need
- `netstandard2.1` compatibility. This is mostly a few polyfill or slight method tweaks
- The game is running in wine, which doesn't have named mutexes, and I want to run studio outside wine anyways, so
- when running in wine use /tmp/ paths
- fix the following exception by ensure the file is large enough (https://stackoverflow.com/a/12251630)
```
[Info] Studio Communication @ Studio: Starting communication...
System.ArgumentOutOfRangeException: The capacity may not be smaller than the file size. (Parameter 'capacity')
at System.IO.MemoryMappedFiles.MemoryMappedFile.VerifyMemoryMappedFileAccess(MemoryMappedFileAccess access, Int64 capacity, SafeFileHandle fileHandle, Int64 fileSize, Boolean& isRegularFile)
at …
```
=> Add support for running under wine + `netstandard2.1` compat

Studio/CelesteStudio/Editing/Editor.cs, Studio/CelesteStudio/Editing/FileRefactor.cs, StudioCommunication/CommandLine.cs
While `console,load,` suggests 1 2 3 4 etc., `console load ` didn't. This is fixed by not trimming the trailing whitespace away when parsing the command line, because it is actually meaningful.
Also closes the popup when you `Ctrl-Y`.
=> Fix completion with trailing whitespace

Studio/CelesteStudio/Editing/Editor.cs
When you have
```lua
14
5,K<|>
***
5,K
10
```
and you type `+1↓`, I'd expect to steal from the 5,K below the savestate.
=> frame ops: steal from next action line

Studio/CelesteStudio/Editing/Editor.cs
Changes it so that when you move up here, the caret moves to line 11 instead of line 20.
I'm not sure whether this is universally preferred. Of course you could add a preference for this, but I'd prefer adding preferences only if people actually use them.
**Current Behaviour**: Notepad
**New Behaviour**: Rider, VS Code, Visual Studio, Google Docs, Word
=> editor: when moving caret, pick location based on selection

CelesteTAS-EverestInterop/Source/InfoHUD/TargetQuery.cs
**Namespaceless types:**
- Previously they would be added twice into `AllTypes`, and any type that exists twice is never autocompleted (this could also be improved).
- now they're autocompleted as well
I know they aren't really used in celeste, but in unity I think it is more common that the namespaceless types are usually the actual game types so they should be displayed first.
In celeste, apparently only `FlagDateTrigger` (modded?) is namespaceless.
**Invoke can call overload based on arity**
If there are both
```
void ChangeState(State newState);
void ChangeState(State newState, State fallback);
```
calling `Invoke` would previously throw an `AmbiguousMatch` exception. Now `Invoke, MonsterBase.ChangeStateIfValid, Attack8` works as expected.
=> Improvements to target query
